#include "dict.h"

Dict getCatA(){

/*Categories ici*/
Dict catA;
catA=DictCreate();

/**************************************************************/
//doc01_artdesign.txt
DictInsert(catA,"designers","0");
DictInsert(catA,"painting","0");
DictInsert(catA,"photo","0");
DictInsert(catA,"photography","0");
DictInsert(catA,"illustrators","0");
DictInsert(catA,"artists","0");
DictInsert(catA,"design","0");
DictInsert(catA,"image","0");
DictInsert(catA,"icons","0");
DictInsert(catA,"identification","0");
DictInsert(catA,"google","0");
DictInsert(catA,"sketching","0");
DictInsert(catA,"fonts","0");
DictInsert(catA,"graphics","0");
DictInsert(catA,"camera","0");
DictInsert(catA,"vector","0");
DictInsert(catA,"editing","0");
DictInsert(catA,"computer","0");
DictInsert(catA,"digital","0");
DictInsert(catA,"art","0");
DictInsert(catA,"interaction","0");
DictInsert(catA,"typeface","0");
DictInsert(catA,"creative","0");
DictInsert(catA,"imagination","0");
DictInsert(catA,"paintings","0");
DictInsert(catA,"illustration","0");
DictInsert(catA,"logo","0");
DictInsert(catA,"creativity","0");
DictInsert(catA,"infographics","0");
DictInsert(catA,"drawing","0");
DictInsert(catA,"logos","0");
DictInsert(catA,"visual","0");
DictInsert(catA,"graphic","0");
DictInsert(catA,"manipulation","0");
DictInsert(catA,"iconography","0");
DictInsert(catA,"arts","0");
DictInsert(catA,"typefaces","0");
DictInsert(catA,"icon","0");
DictInsert(catA,"cameras","0");


/**************************************************************/
//doc02_betsgambl.txt
DictInsert(catA,"online","1");
DictInsert(catA,"bets","1");
DictInsert(catA,"buying","1");
DictInsert(catA,"funds","1");
DictInsert(catA,"wall","1");
DictInsert(catA,"risk","1");
DictInsert(catA,"money","1");
DictInsert(catA,"order","1");
DictInsert(catA,"hedge","1");
DictInsert(catA,"selling","1");
DictInsert(catA,"gamble","1");
DictInsert(catA,"prices","1");
DictInsert(catA,"bet","1");
DictInsert(catA,"internet","1");
DictInsert(catA,"trading","1");
DictInsert(catA,"losses","1");
DictInsert(catA,"casino","1");
DictInsert(catA,"long","1");
DictInsert(catA,"million","1");
DictInsert(catA,"casinos","1");
DictInsert(catA,"trade","1");
DictInsert(catA,"street","1");
DictInsert(catA,"options","1");
DictInsert(catA,"gambling","1");
DictInsert(catA,"sell","1");
DictInsert(catA,"betting","1");
DictInsert(catA,"gamblers","1");
DictInsert(catA,"traders","1");


/**************************************************************/
//doc03_booksdddd.txt
DictInsert(catA,"self-publishing","2");
DictInsert(catA,"fiction","2");
DictInsert(catA,"books","2");
DictInsert(catA,"getting","2");
DictInsert(catA,"fantasy","2");
DictInsert(catA,"american","2");
DictInsert(catA,"young","2");
DictInsert(catA,"children’s","2");
DictInsert(catA,"ebooks","2");
DictInsert(catA,"published","2");
DictInsert(catA,"literary","2");
DictInsert(catA,"fictional","2");
DictInsert(catA,"authors","2");
DictInsert(catA,"ibooks","2");
DictInsert(catA,"characters","2");
DictInsert(catA,"readers","2");
DictInsert(catA,"publishing","2");
DictInsert(catA,"non-fiction","2");
DictInsert(catA,"poetry","2");
DictInsert(catA,"recommendations","2");
DictInsert(catA,"short","2");
DictInsert(catA,"stories","2");
DictInsert(catA,"adult","2");
DictInsert(catA,"ebook","2");
DictInsert(catA,"literature","2");
DictInsert(catA,"kindle","2");


/**************************************************************/
//doc04_businesse.txt
DictInsert(catA,"small","3");
DictInsert(catA,"sme","3");
DictInsert(catA,"import","3");
DictInsert(catA,"consulting","3");
DictInsert(catA,"export","3");
DictInsert(catA,"design","3");
DictInsert(catA,"ecommerce","3");
DictInsert(catA,"organizational","3");
DictInsert(catA,"models","3");
DictInsert(catA,"entrepreneurs","3");
DictInsert(catA,"agencies","3");
DictInsert(catA,"strategy","3");
DictInsert(catA,"behavior","3");
DictInsert(catA,"local","3");
DictInsert(catA,"resources","3");
DictInsert(catA,"advice","3");
DictInsert(catA,"leadership","3");
DictInsert(catA,"industrial","3");
DictInsert(catA,"project","3");
DictInsert(catA,"social","3");
DictInsert(catA,"digital","3");
DictInsert(catA,"administration","3");
DictInsert(catA,"business","3");
DictInsert(catA,"owner","3");
DictInsert(catA,"medium","3");
DictInsert(catA,"retail","3");
DictInsert(catA,"businesses","3");
DictInsert(catA,"human","3");
DictInsert(catA,"organization","3");
DictInsert(catA,"companies","3");
DictInsert(catA,"leaders","3");
DictInsert(catA,"marketing","3");
DictInsert(catA,"brick","3");
DictInsert(catA,"enterprise","3");
DictInsert(catA,"strategic","3");
DictInsert(catA,"relationships","3");
DictInsert(catA,"culture","3");
DictInsert(catA,"management","3");
DictInsert(catA,"business-to-business","3");
DictInsert(catA,"mortar","3");
DictInsert(catA,"plans","3");
DictInsert(catA,"entrepreneurship","3");
DictInsert(catA,"networking","3");


/**************************************************************/
//doc05_carsother.txt
DictInsert(catA,"bmw","4");
DictInsert(catA,"model","4");
DictInsert(catA,"hertz","4");
DictInsert(catA,"rent","4");
DictInsert(catA,"toyota","4");
DictInsert(catA,"parts","4");
DictInsert(catA,"ford","4");
DictInsert(catA,"corvette","4");
DictInsert(catA,"part","4");
DictInsert(catA,"dealer","4");
DictInsert(catA,"honda","4");
DictInsert(catA,"wash","4");
DictInsert(catA,"crv","4");
DictInsert(catA,"rental","4");
DictInsert(catA,"sale","4");
DictInsert(catA,"trucks","4");
DictInsert(catA,"vehicle","4");
DictInsert(catA,"dealership","4");
DictInsert(catA,"automobile","4");
DictInsert(catA,"vehicles","4");
DictInsert(catA,"cars","4");
DictInsert(catA,"used","4");
DictInsert(catA,"sales","4");
DictInsert(catA,"truck","4");
DictInsert(catA,"car","4");
DictInsert(catA,"auto","4");
DictInsert(catA,"tesla","4");


/**************************************************************/
//doc06_celebriti.txt
DictInsert(catA,"celebrities","5");
DictInsert(catA,"dignitaries","5");
DictInsert(catA,"artists","5");
DictInsert(catA,"figures","5");
DictInsert(catA,"lifestyle","5");
DictInsert(catA,"kardashian","5");
DictInsert(catA,"zendaya","5");
DictInsert(catA,"entertainers","5");
DictInsert(catA,"fame","5");
DictInsert(catA,"pitt","5");
DictInsert(catA,"life","5");
DictInsert(catA,"perfomers","5");
DictInsert(catA,"lives","5");
DictInsert(catA,"kylie","5");
DictInsert(catA,"lopez","5");
DictInsert(catA,"brad","5");
DictInsert(catA,"jenniffer","5");
DictInsert(catA,"habit","5");
DictInsert(catA,"personalities","5");
DictInsert(catA,"artistes","5");
DictInsert(catA,"kim","5");
DictInsert(catA,"celebrity","5");
DictInsert(catA,"livelihood","5");
DictInsert(catA,"evans","5");
DictInsert(catA,"jenner","5");
DictInsert(catA,"notables","5");
DictInsert(catA,"chris","5");
DictInsert(catA,"featured","5");


/**************************************************************/
//doc07_cryptocur.txt
DictInsert(catA,"binance","6");
DictInsert(catA,"stellar","6");
DictInsert(catA,"ltc","6");
DictInsert(catA,"btc","6");
DictInsert(catA,"litecoin","6");
DictInsert(catA,"bitcoin","6");
DictInsert(catA,"cash","6");
DictInsert(catA,"ethereum","6");
DictInsert(catA,"xmr","6");
DictInsert(catA,"crypto","6");
DictInsert(catA,"ada","6");
DictInsert(catA,"polkadot","6");
DictInsert(catA,"cardano","6");
DictInsert(catA,"bnb","6");
DictInsert(catA,"cryptocurrencies","6");
DictInsert(catA,"chainlink","6");
DictInsert(catA,"bch","6");
DictInsert(catA,"dot","6");
DictInsert(catA,"monero","6");
DictInsert(catA,"cryptocurrency","6");
DictInsert(catA,"usdt","6");
DictInsert(catA,"currency","6");
DictInsert(catA,"tether","6");
DictInsert(catA,"xlm","6");
DictInsert(catA,"eth","6");
DictInsert(catA,"coin","6");


/**************************************************************/
//doc08_cultureev.txt
DictInsert(catA,"traditions","7");
DictInsert(catA,"heritage","7");
DictInsert(catA,"mindset","7");
DictInsert(catA,"events","7");
DictInsert(catA,"multiculture","7");
DictInsert(catA,"culture","7");
DictInsert(catA,"culturally","7");
DictInsert(catA,"ethos","7");
DictInsert(catA,"attitude","7");
DictInsert(catA,"tradition","7");
DictInsert(catA,"intercultural","7");
DictInsert(catA,"philosophy","7");
DictInsert(catA,"event","7");


/**************************************************************/
//doc09_curiousfa.txt
DictInsert(catA,"know","8");
DictInsert(catA,"facts","8");
DictInsert(catA,"curiosity","8");
DictInsert(catA,"curious","8");
DictInsert(catA,"exquisite","8");
DictInsert(catA,"question","8");
DictInsert(catA,"knowledge","8");


/**************************************************************/
//doc10_directori.txt
DictInsert(catA,"channels","9");
DictInsert(catA,"directories","9");
DictInsert(catA,"bot","9");
DictInsert(catA,"bots","9");


/**************************************************************/
//doc11_economyfi.txt
DictInsert(catA,"funding","10");
DictInsert(catA,"investing","10");
DictInsert(catA,"stock","10");
DictInsert(catA,"macro","10");
DictInsert(catA,"history","10");
DictInsert(catA,"money","10");
DictInsert(catA,"life","10");
DictInsert(catA,"currencies","10");
DictInsert(catA,"fundraising","10");
DictInsert(catA,"accounting","10");
DictInsert(catA,"economic","10");
DictInsert(catA,"equity","10");
DictInsert(catA,"taxes","10");
DictInsert(catA,"personal","10");
DictInsert(catA,"market","10");
DictInsert(catA,"microeconomics","10");
DictInsert(catA,"finances","10");
DictInsert(catA,"capitalism","10");
DictInsert(catA,"daily","10");
DictInsert(catA,"economics","10");
DictInsert(catA,"inflation","10");
DictInsert(catA,"private","10");
DictInsert(catA,"mathematics","10");
DictInsert(catA,"investors","10");
DictInsert(catA,"finance","10");
DictInsert(catA,"economy","10");


/**************************************************************/
//doc12_education.txt
DictInsert(catA,"lessons","11");
DictInsert(catA,"science","11");
DictInsert(catA,"teachers","11");
DictInsert(catA,"curricula","11");
DictInsert(catA,"lesson","11");
DictInsert(catA,"curriculum","11");
DictInsert(catA,"understand","11");
DictInsert(catA,"teaching","11");
DictInsert(catA,"commerce","11");
DictInsert(catA,"pedagogy","11");
DictInsert(catA,"schools","11");
DictInsert(catA,"schooling","11");
DictInsert(catA,"agriculture","11");
DictInsert(catA,"education","11");
DictInsert(catA,"physics","11");
DictInsert(catA,"homeschooling","11");
DictInsert(catA,"engineering","11");
DictInsert(catA,"biology","11");
DictInsert(catA,"training","11");
DictInsert(catA,"learn","11");
DictInsert(catA,"statistics","11");
DictInsert(catA,"chemistry","11");
DictInsert(catA,"mathematiques","11");
DictInsert(catA,"school","11");
DictInsert(catA,"maths","11");
DictInsert(catA,"instruction","11");
DictInsert(catA,"geography","11");


/**************************************************************/
//doc13_eroticcon.txt
DictInsert(catA,"lesbian","12");
DictInsert(catA,"vice","12");
DictInsert(catA,"sexy","12");
DictInsert(catA,"nudy","12");
DictInsert(catA,"dick","12");
DictInsert(catA,"milf","12");
DictInsert(catA,"fucking","12");
DictInsert(catA,"pussy","12");
DictInsert(catA,"sex","12");
DictInsert(catA,"porno","12");
DictInsert(catA,"hot","12");
DictInsert(catA,"shemale","12");
DictInsert(catA,"content","12");
DictInsert(catA,"teenager","12");
DictInsert(catA,"pornographic","12");
DictInsert(catA,"lick","12");
DictInsert(catA,"fuck","12");
DictInsert(catA,"lingerie","12");
DictInsert(catA,"movie","12");
DictInsert(catA,"erotic","12");
DictInsert(catA,"love","12");
DictInsert(catA,"porn","12");
DictInsert(catA,"gay","12");
DictInsert(catA,"sensual","12");
DictInsert(catA,"vagina","12");
DictInsert(catA,"nudie","12");
DictInsert(catA,"nudes","12");


/**************************************************************/
//doc14_fashionbe.txt
DictInsert(catA,"mens","13");
DictInsert(catA,"garment","13");
DictInsert(catA,"forge","13");
DictInsert(catA,"men's","13");
DictInsert(catA,"cute","13");
DictInsert(catA,"couture","13");
DictInsert(catA,"women's","13");
DictInsert(catA,"cloth","13");
DictInsert(catA,"clothing","13");
DictInsert(catA,"outfit","13");
DictInsert(catA,"apparel","13");
DictInsert(catA,"attire","13");
DictInsert(catA,"manner","13");
DictInsert(catA,"style","13");
DictInsert(catA,"fashion","13");
DictInsert(catA,"garments","13");
DictInsert(catA,"moda","13");
DictInsert(catA,"beauty","13");
DictInsert(catA,"dresses","13");
DictInsert(catA,"womans","13");
DictInsert(catA,"figure","13");
DictInsert(catA,"dress","13");
DictInsert(catA,"styling","13");


/**************************************************************/
//doc15_fitnessdd.txt
DictInsert(catA,"physical","14");
DictInsert(catA,"exercises","14");
DictInsert(catA,"stamina","14");
DictInsert(catA,"fitness","14");
DictInsert(catA,"gym","14");
DictInsert(catA,"workout","14");
DictInsert(catA,"physique","14");
DictInsert(catA,"health","14");
DictInsert(catA,"rogue","14");
DictInsert(catA,"aerobics","14");
DictInsert(catA,"training","14");
DictInsert(catA,"abs","14");


/**************************************************************/
//doc16_foodcooki.txt
DictInsert(catA,"recipe","15");
DictInsert(catA,"cuisine","15");
DictInsert(catA,"chef","15");
DictInsert(catA,"ktchens","15");
DictInsert(catA,"cookery","15");
DictInsert(catA,"dessert","15");
DictInsert(catA,"recipes","15");
DictInsert(catA,"dinner","15");
DictInsert(catA,"mix","15");
DictInsert(catA,"cookbook","15");
DictInsert(catA,"oven","15");
DictInsert(catA,"food","15");
DictInsert(catA,"chicken","15");
DictInsert(catA,"nutrient","15");
DictInsert(catA,"baking","15");
DictInsert(catA,"meal","15");
DictInsert(catA,"nutritional","15");
DictInsert(catA,"cooking","15");
DictInsert(catA,"seafood","15");
DictInsert(catA,"wait","15");
DictInsert(catA,"frying","15");
DictInsert(catA,"minutes","15");
DictInsert(catA,"gourmet","15");
DictInsert(catA,"breast","15");
DictInsert(catA,"eat","15");
DictInsert(catA,"stove","15");


/**************************************************************/
//doc17_foreignla.txt
DictInsert(catA,"language","16");
DictInsert(catA,"learn","16");
DictInsert(catA,"speak","16");
DictInsert(catA,"pronounce","16");
DictInsert(catA,"learning","16");
DictInsert(catA,"pronounciation","16");
DictInsert(catA,"fluently","16");
DictInsert(catA,"fluent","16");
DictInsert(catA,"speaking","16");
DictInsert(catA,"pronouncing","16");


/**************************************************************/
//doc18_healthmed.txt
DictInsert(catA,"heartburn","17");
DictInsert(catA,"herbalist","17");
DictInsert(catA,"pain","17");
DictInsert(catA,"pressure","17");
DictInsert(catA,"epidemiology","17");
DictInsert(catA,"antihistamine","17");
DictInsert(catA,"depression","17");
DictInsert(catA,"sore","17");
DictInsert(catA,"health","17");
DictInsert(catA,"cough","17");
DictInsert(catA,"allergy","17");
DictInsert(catA,"blood","17");
DictInsert(catA,"remedies","17");
DictInsert(catA,"killer","17");
DictInsert(catA,"throat","17");
DictInsert(catA,"weight","17");
DictInsert(catA,"sick","17");
DictInsert(catA,"treatment","17");
DictInsert(catA,"medication","17");
DictInsert(catA,"medicine","17");
DictInsert(catA,"care","17");
DictInsert(catA,"yeast","17");
DictInsert(catA,"infection","17");
DictInsert(catA,"disease","17");


/**************************************************************/
//doc19_historydd.txt
DictInsert(catA,"government","18");
DictInsert(catA,"wars","18");
DictInsert(catA,"world","18");
DictInsert(catA,"national","18");
DictInsert(catA,"chronicle","18");
DictInsert(catA,"brief","18");
DictInsert(catA,"time","18");
DictInsert(catA,"histories","18");
DictInsert(catA,"museum","18");
DictInsert(catA,"black","18");
DictInsert(catA,"tactics","18");
DictInsert(catA,"war","18");
DictInsert(catA,"military","18");
DictInsert(catA,"history","18");
DictInsert(catA,"battle","18");


/**************************************************************/
//doc20_hobbiesac.txt
DictInsert(catA,"activities","19");
DictInsert(catA,"interests","19");
DictInsert(catA,"common","19");
DictInsert(catA,"hobby","19");
DictInsert(catA,"interest","19");
DictInsert(catA,"hobbies","19");


/**************************************************************/
//doc21_homearchi.txt
DictInsert(catA,"contemporary","20");
DictInsert(catA,"design","20");
DictInsert(catA,"courtyard","20");
DictInsert(catA,"traditional","20");
DictInsert(catA,"victorian","20");
DictInsert(catA,"tudor","20");
DictInsert(catA,"architectural","20");
DictInsert(catA,"housing","20");
DictInsert(catA,"style","20");
DictInsert(catA,"architect","20");
DictInsert(catA,"modern","20");
DictInsert(catA,"homes","20");
DictInsert(catA,"century","20");
DictInsert(catA,"architects","20");
DictInsert(catA,"mid","20");
DictInsert(catA,"home","20");
DictInsert(catA,"colonial","20");
DictInsert(catA,"architecture","20");
DictInsert(catA,"house","20");
DictInsert(catA,"plans","20");
DictInsert(catA,"craftsman","20");


/**************************************************************/
//doc22_humormeme.txt
DictInsert(catA,"funny","21");
DictInsert(catA,"humor","21");
DictInsert(catA,"anime","21");
DictInsert(catA,"joke","21");
DictInsert(catA,"dark","21");
DictInsert(catA,"memes","21");
DictInsert(catA,"meme","21");
DictInsert(catA,"jokes","21");
DictInsert(catA,"fun","21");
DictInsert(catA,"funniest","21");


/**************************************************************/
//doc23_investmen.txt
DictInsert(catA,"funding","22");
DictInsert(catA,"investing","22");
DictInsert(catA,"ideas","22");
DictInsert(catA,"angel","22");
DictInsert(catA,"entrepreneurs","22");
DictInsert(catA,"intellectual","22");
DictInsert(catA,"buy","22");
DictInsert(catA,"growth","22");
DictInsert(catA,"young","22");
DictInsert(catA,"hold","22");
DictInsert(catA,"patents","22");
DictInsert(catA,"venture","22");
DictInsert(catA,"seed","22");
DictInsert(catA,"recruiting","22");
DictInsert(catA,"trademarks","22");
DictInsert(catA,"startups","22");
DictInsert(catA,"equity","22");
DictInsert(catA,"bootstrapping","22");
DictInsert(catA,"firms","22");
DictInsert(catA,"infringement","22");
DictInsert(catA,"stocks","22");
DictInsert(catA,"innovation","22");
DictInsert(catA,"internet","22");
DictInsert(catA,"market","22");
DictInsert(catA,"business","22");
DictInsert(catA,"copyright","22");
DictInsert(catA,"compensation","22");
DictInsert(catA,"acquisitions","22");
DictInsert(catA,"crowdfunding","22");
DictInsert(catA,"hacking","22");
DictInsert(catA,"invest","22");
DictInsert(catA,"valuations","22");
DictInsert(catA,"hiring","22");
DictInsert(catA,"open","22");
DictInsert(catA,"property","22");
DictInsert(catA,"futures","22");
DictInsert(catA,"investors","22");
DictInsert(catA,"mergers","22");
DictInsert(catA,"investments","22");
DictInsert(catA,"sell","22");
DictInsert(catA,"pre-launch","22");
DictInsert(catA,"price","22");
DictInsert(catA,"law","22");
DictInsert(catA,"capital","22");
DictInsert(catA,"co-founders","22");


/**************************************************************/
//doc24_joblistin.txt
DictInsert(catA,"information","23");
DictInsert(catA,"able","23");
DictInsert(catA,"complex","23");
DictInsert(catA,"service","23");
DictInsert(catA,"providing","23");
DictInsert(catA,"provide","23");
DictInsert(catA,"project","23");
DictInsert(catA,"available|travel","23");
DictInsert(catA,"assigned","23");
DictInsert(catA,"team","23");
DictInsert(catA,"customer","23");
DictInsert(catA,"client","23");
DictInsert(catA,"services","23");
DictInsert(catA,"days","23");
DictInsert(catA,"opportunity","23");
DictInsert(catA,"technical","23");
DictInsert(catA,"training","23");
DictInsert(catA,"ensure","23");
DictInsert(catA,"years","23");
DictInsert(catA,"knowledge","23");
DictInsert(catA,"testing","23");
DictInsert(catA,"working","23");
DictInsert(catA,"care","23");
DictInsert(catA,"time","23");
DictInsert(catA,"management","23");
DictInsert(catA,"work","23");
DictInsert(catA,"required","23");
DictInsert(catA,"tools","23");
DictInsert(catA,"projects","23");
DictInsert(catA,"technologies","23");
DictInsert(catA,"skills","23");
DictInsert(catA,"job","23");
DictInsert(catA,"candidate","23");
DictInsert(catA,"security","23");
DictInsert(catA,"customers","23");
DictInsert(catA,"engineer","23");
DictInsert(catA,"business","23");
DictInsert(catA,"degree","23");
DictInsert(catA,"duties","23");
DictInsert(catA,"software","23");
DictInsert(catA,"looking","23");
DictInsert(catA,"server","23");
DictInsert(catA,"including","23");
DictInsert(catA,"contract","23");
DictInsert(catA,"application","23");
DictInsert(catA,"multiple","23");
DictInsert(catA,"teams","23");
DictInsert(catA,"level","23");
DictInsert(catA,"corp-to-corp","23");
DictInsert(catA,"listing","23");
DictInsert(catA,"responsible","23");
DictInsert(catA,"applications","23");
DictInsert(catA,"position","23");
DictInsert(catA,"health","23");
DictInsert(catA,"technology","23");
DictInsert(catA,"performance","23");
DictInsert(catA,"user","23");
DictInsert(catA,"quality","23");
DictInsert(catA,"role","23");
DictInsert(catA,"independent","23");
DictInsert(catA,"product","23");
DictInsert(catA,"related","23");
DictInsert(catA,"listings","23");
DictInsert(catA,"school","23");
DictInsert(catA,"sales","23");
DictInsert(catA,"understanding","23");
DictInsert(catA,"process","23");
DictInsert(catA,"requirements","23");
DictInsert(catA,"systems","23");
DictInsert(catA,"and/or","23");
DictInsert(catA,"design","23");
DictInsert(catA,"communication","23");
DictInsert(catA,"development","23");
DictInsert(catA,"best","23");
DictInsert(catA,"system","23");
DictInsert(catA,"environment","23");
DictInsert(catA,"develop","23");
DictInsert(catA,"experience","23");
DictInsert(catA,"ability","23");
DictInsert(catA,"computer","23");
DictInsert(catA,"support","23");
DictInsert(catA,"jobs","23");
DictInsert(catA,"solutions","23");
DictInsert(catA,"engineering","23");
DictInsert(catA,"high","23");
DictInsert(catA,"company","23");
DictInsert(catA,"data","23");
DictInsert(catA,"enterprise","23");
DictInsert(catA,"developer","23");
DictInsert(catA,"staff","23");
DictInsert(catA,"strong","23");


/**************************************************************/
//doc25_kidsparen.txt
DictInsert(catA,"guide","24");
DictInsert(catA,"motherhood","24");
DictInsert(catA,"locker","24");
DictInsert(catA,"parenting","24");
DictInsert(catA,"talk","24");
DictInsert(catA,"pages","24");
DictInsert(catA,"barn","24");
DictInsert(catA,"fatherhood","24");
DictInsert(catA,"authoritarian","24");
DictInsert(catA,"coloring","24");
DictInsert(catA,"single","24");
DictInsert(catA,"pottery","24");
DictInsert(catA,"kids","24");
DictInsert(catA,"styles","24");
DictInsert(catA,"parent","24");
DictInsert(catA,"kid","24");
DictInsert(catA,"foot","24");


/**************************************************************/
//doc26_marketing.txt
DictInsert(catA,"production","25");
DictInsert(catA,"mottos","25");
DictInsert(catA,"advertising","25");
DictInsert(catA,"online","25");
DictInsert(catA,"names","25");
DictInsert(catA,"planning","25");
DictInsert(catA,"reputation","25");
DictInsert(catA,"video","25");
DictInsert(catA,"affiliate","25");
DictInsert(catA,"taglines","25");
DictInsert(catA,"blog","25");
DictInsert(catA,"naming","25");
DictInsert(catA,"conventions","25");
DictInsert(catA,"professional","25");
DictInsert(catA,"speaking","25");
DictInsert(catA,"agencies","25");
DictInsert(catA,"b2b","25");
DictInsert(catA,"strategy","25");
DictInsert(catA,"mobile","25");
DictInsert(catA,"branding","25");
DictInsert(catA,"conferences","25");
DictInsert(catA,"news-letters","25");
DictInsert(catA,"broadcast","25");
DictInsert(catA,"advice","25");
DictInsert(catA,"editing","25");
DictInsert(catA,"content","25");
DictInsert(catA,"deliverability","25");
DictInsert(catA,"internet","25");
DictInsert(catA,"personal","25");
DictInsert(catA,"social","25");
DictInsert(catA,"brands","25");
DictInsert(catA,"awareness","25");
DictInsert(catA,"press","25");
DictInsert(catA,"new","25");
DictInsert(catA,"hashtags","25");
DictInsert(catA,"friends","25");
DictInsert(catA,"client","25");
DictInsert(catA,"relations","25");
DictInsert(catA,"movie","25");
DictInsert(catA,"graph","25");
DictInsert(catA,"media","25");
DictInsert(catA,"web","25");
DictInsert(catA,"people","25");
DictInsert(catA,"print","25");
DictInsert(catA,"clients","25");
DictInsert(catA,"printing","25");
DictInsert(catA,"making","25");
DictInsert(catA,"event","25");
DictInsert(catA,"email","25");
DictInsert(catA,"marketing","25");
DictInsert(catA,"blogs","25");
DictInsert(catA,"public","25");
DictInsert(catA,"commercial","25");
DictInsert(catA,"slogans","25");
DictInsert(catA,"newsletters","25");
DictInsert(catA,"product","25");
DictInsert(catA,"brand","25");
DictInsert(catA,"blogging","25");
DictInsert(catA,"management","25");
DictInsert(catA,"releases","25");
DictInsert(catA,"guest","25");
DictInsert(catA,"meeting","25");
DictInsert(catA,"newsletter","25");
DictInsert(catA,"cinematography","25");
DictInsert(catA,"spam","25");
DictInsert(catA,"networking","25");


/**************************************************************/
//doc27_motivatio.txt
DictInsert(catA,"attention","26");
DictInsert(catA,"self","26");
DictInsert(catA,"work-life","26");
DictInsert(catA,"productivity","26");
DictInsert(catA,"organizing","26");
DictInsert(catA,"systems","26");
DictInsert(catA,"motivation","26");
DictInsert(catA,"ambitions","26");
DictInsert(catA,"getting","26");
DictInsert(catA,"system","26");
DictInsert(catA,"distractions","26");
DictInsert(catA,"skills","26");
DictInsert(catA,"mastermind","26");
DictInsert(catA,"improvements","26");
DictInsert(catA,"hacks","26");
DictInsert(catA,"tasks","26");
DictInsert(catA,"habits","26");
DictInsert(catA,"ambition","26");
DictInsert(catA,"things","26");
DictInsert(catA,"distraction","26");
DictInsert(catA,"learning","26");
DictInsert(catA,"inspiration","26");
DictInsert(catA,"goals","26");
DictInsert(catA,"focus","26");
DictInsert(catA,"self-development","26");
DictInsert(catA,"personal","26");
DictInsert(catA,"improvement","26");
DictInsert(catA,"caledaring","26");
DictInsert(catA,"bad","26");
DictInsert(catA,"concentration","26");
DictInsert(catA,"done","26");
DictInsert(catA,"procrastination","26");
DictInsert(catA,"success","26");
DictInsert(catA,"setting","26");
DictInsert(catA,"organization","26");
DictInsert(catA,"goal","26");
DictInsert(catA,"conversations","26");
DictInsert(catA,"thing","26");
DictInsert(catA,"habit","26");
DictInsert(catA,"scheduling","26");
DictInsert(catA,"routines","26");
DictInsert(catA,"skill","26");
DictInsert(catA,"tip","26");
DictInsert(catA,"task","26");
DictInsert(catA,"hack","26");
DictInsert(catA,"routine","26");
DictInsert(catA,"thinking","26");
DictInsert(catA,"management","26");
DictInsert(catA,"balance","26");
DictInsert(catA,"conversation","26");
DictInsert(catA,"tips","26");
DictInsert(catA,"masterminds","26");


/**************************************************************/
//doc28_moviesddd.txt
DictInsert(catA,"free","27");
DictInsert(catA,"show","27");
DictInsert(catA,"hbo","27");
DictInsert(catA,"hedgehog","27");
DictInsert(catA,"soap2day","27");
DictInsert(catA,"gentlen","27");
DictInsert(catA,"sonic","27");
DictInsert(catA,"harry","27");
DictInsert(catA,"scary","27");
DictInsert(catA,"season","27");
DictInsert(catA,"film","27");
DictInsert(catA,"netflix","27");
DictInsert(catA,"movies","27");
DictInsert(catA,"video","27");
DictInsert(catA,"potter","27");
DictInsert(catA,"best","27");
DictInsert(catA,"episode","27");
DictInsert(catA,"frozen","27");


/**************************************************************/
//doc29_musicdddd.txt
DictInsert(catA,"eminem","28");
DictInsert(catA,"bocelli","28");
DictInsert(catA,"jazz","28");
DictInsert(catA,"sound","28");
DictInsert(catA,"downloader","28");
DictInsert(catA,"andrea","28");
DictInsert(catA,"mars","28");
DictInsert(catA,"song","28");
DictInsert(catA,"spotify","28");
DictInsert(catA,"bruno","28");
DictInsert(catA,"rick","28");
DictInsert(catA,"apple","28");
DictInsert(catA,"notes","28");
DictInsert(catA,"tunes","28");
DictInsert(catA,"mp3","28");
DictInsert(catA,"play","28");
DictInsert(catA,"download","28");
DictInsert(catA,"youtube","28");
DictInsert(catA,"music","28");
DictInsert(catA,"ross","28");
DictInsert(catA,"guitar","28");


/**************************************************************/
//doc30_offerspro.txt
DictInsert(catA,"extends","29");
DictInsert(catA,"offer","29");
DictInsert(catA,"extended","29");
DictInsert(catA,"coupon","29");
DictInsert(catA,"coupons","29");
DictInsert(catA,"promo","29");
DictInsert(catA,"promotion","29");
DictInsert(catA,"offers","29");
DictInsert(catA,"target","29");
DictInsert(catA,"friday","29");
DictInsert(catA,"black","29");
DictInsert(catA,"promotions","29");
DictInsert(catA,"sale","29");
DictInsert(catA,"sales","29");
DictInsert(catA,"code","29");
DictInsert(catA,"staples","29");


/**************************************************************/
//doc31_petsddddd.txt
DictInsert(catA,"pumps","30");
DictInsert(catA,"bernese","30");
DictInsert(catA,"grooming","30");
DictInsert(catA,"pets","30");
DictInsert(catA,"manufacturers","30");
DictInsert(catA,"aquariums","30");
DictInsert(catA,"pug","30");
DictInsert(catA,"lighting","30");
DictInsert(catA,"papillon","30");
DictInsert(catA,"newfoundland","30");
DictInsert(catA,"akita","30");
DictInsert(catA,"organi","30");
DictInsert(catA,"cat","30");
DictInsert(catA,"pet","30");
DictInsert(catA,"food","30");
DictInsert(catA,"suppliers","30");
DictInsert(catA,"aquarium","30");
DictInsert(catA,"mountain","30");
DictInsert(catA,"boxer","30");
DictInsert(catA,"treats","30");
DictInsert(catA,"sale","30");
DictInsert(catA,"puppy","30");
DictInsert(catA,"raw","30");
DictInsert(catA,"filters","30");
DictInsert(catA,"complete","30");
DictInsert(catA,"dog","30");
DictInsert(catA,"puppies","30");
DictInsert(catA,"maltese","30");
DictInsert(catA,"heaters","30");


/**************************************************************/
//doc32_politicsi.txt
DictInsert(catA,"defense","31");
DictInsert(catA,"vice","31");
DictInsert(catA,"accident","31");
DictInsert(catA,"elections","31");
DictInsert(catA,"liasson","31");
DictInsert(catA,"aviation","31");
DictInsert(catA,"party","31");
DictInsert(catA,"army","31");
DictInsert(catA,"presidential","31");
DictInsert(catA,"police","31");
DictInsert(catA,"democrat","31");
DictInsert(catA,"election","31");
DictInsert(catA,"president","31");
DictInsert(catA,"fire","31");
DictInsert(catA,"politics","31");
DictInsert(catA,"country","31");
DictInsert(catA,"dictator","31");
DictInsert(catA,"dictatorship","31");
DictInsert(catA,"minister","31");
DictInsert(catA,"government","31");
DictInsert(catA,"incidents","31");
DictInsert(catA,"general","31");
DictInsert(catA,"independent","31");
DictInsert(catA,"democratic","31");
DictInsert(catA,"traffic","31");
DictInsert(catA,"deputy","31");


/**************************************************************/
//doc33_psycholog.txt
DictInsert(catA,"emotion","32");
DictInsert(catA,"emotions","32");
DictInsert(catA,"everyday","32");
DictInsert(catA,"relationship","32");
DictInsert(catA,"communication","32");
DictInsert(catA,"indicator","32");
DictInsert(catA,"anxiety","32");
DictInsert(catA,"introvert","32");
DictInsert(catA,"behavior","32");
DictInsert(catA,"life","32");
DictInsert(catA,"type","32");
DictInsert(catA,"nonverbal","32");
DictInsert(catA,"introversion","32");
DictInsert(catA,"health","32");
DictInsert(catA,"introverts","32");
DictInsert(catA,"behavioral","32");
DictInsert(catA,"personality","32");
DictInsert(catA,"morals","32");
DictInsert(catA,"psychology","32");
DictInsert(catA,"society","32");
DictInsert(catA,"entp","32");
DictInsert(catA,"philosphy","32");
DictInsert(catA,"extroverts","32");
DictInsert(catA,"human","32");
DictInsert(catA,"myers-briggs","32");
DictInsert(catA,"psychiatry","32");
DictInsert(catA,"extrovert","32");
DictInsert(catA,"briggs","32");
DictInsert(catA,"mental","32");
DictInsert(catA,"disc","32");
DictInsert(catA,"neuroscience","32");
DictInsert(catA,"morality","32");
DictInsert(catA,"traits","32");
DictInsert(catA,"intj","32");
DictInsert(catA,"infj","32");
DictInsert(catA,"relationships","32");
DictInsert(catA,"norms","32");
DictInsert(catA,"extroversion","32");
DictInsert(catA,"abnormal","32");
DictInsert(catA,"intp","32");
DictInsert(catA,"advice","32");
DictInsert(catA,"enfp","32");
DictInsert(catA,"myers","32");


/**************************************************************/
//doc34_realestat.txt
DictInsert(catA,"homes","33");
DictInsert(catA,"houses","33");
DictInsert(catA,"list","33");
DictInsert(catA,"masions","33");
DictInsert(catA,"agent","33");
DictInsert(catA,"estate","33");
DictInsert(catA,"realtor","33");
DictInsert(catA,"commercial","33");
DictInsert(catA,"home","33");
DictInsert(catA,"lawyer","33");
DictInsert(catA,"listings","33");
DictInsert(catA,"attorney","33");
DictInsert(catA,"sale","33");
DictInsert(catA,"house","33");
DictInsert(catA,"buy","33");
DictInsert(catA,"land","33");
DictInsert(catA,"real","33");


/**************************************************************/
//doc35_recreatio.txt
DictInsert(catA,"lake","34");
DictInsert(catA,"regional","34");
DictInsert(catA,"entertainment","34");
DictInsert(catA,"canyon","34");
DictInsert(catA,"outdoor","34");
DictInsert(catA,"parks","34");
DictInsert(catA,"recreation","34");
DictInsert(catA,"glen","34");
DictInsert(catA,"center","34");
DictInsert(catA,"creative","34");
DictInsert(catA,"dream","34");
DictInsert(catA,"gorge","34");
DictInsert(catA,"therapeutic","34");
DictInsert(catA,"scotts","34");
DictInsert(catA,"deam","34");
DictInsert(catA,"park","34");
DictInsert(catA,"adult","34");
DictInsert(catA,"rec","34");
DictInsert(catA,"public","34");
DictInsert(catA,"flamming","34");
DictInsert(catA,"city","34");


/**************************************************************/
//doc36_religions.txt
DictInsert(catA,"pagan","35");
DictInsert(catA,"realm","35");
DictInsert(catA,"bible","35");
DictInsert(catA,"rastafari","35");
DictInsert(catA,"polytheism","35");
DictInsert(catA,"yoga","35");
DictInsert(catA,"faith","35");
DictInsert(catA,"paganism","35");
DictInsert(catA,"mormon","35");
DictInsert(catA,"bhudha","35");
DictInsert(catA,"spirit","35");
DictInsert(catA,"religion","35");
DictInsert(catA,"pray","35");
DictInsert(catA,"belief","35");
DictInsert(catA,"hindu","35");
DictInsert(catA,"qoutes","35");
DictInsert(catA,"christianity","35");
DictInsert(catA,"jehovah","35");
DictInsert(catA,"true","35");
DictInsert(catA,"agnoticism","35");
DictInsert(catA,"gnosticism","35");
DictInsert(catA,"enlightenment","35");
DictInsert(catA,"bad","35");
DictInsert(catA,"body","35");
DictInsert(catA,"spritual","35");
DictInsert(catA,"bhudhism","35");
DictInsert(catA,"jesus","35");
DictInsert(catA,"spirituality","35");
DictInsert(catA,"god","35");
DictInsert(catA,"wellness","35");
DictInsert(catA,"awakening","35");
DictInsert(catA,"good","35");
DictInsert(catA,"torah","35");
DictInsert(catA,"guide","35");
DictInsert(catA,"verse","35");
DictInsert(catA,"santeria","35");
DictInsert(catA,"atheist","35");
DictInsert(catA,"zoroastrianism","35");
DictInsert(catA,"witness","35");
DictInsert(catA,"quran","35");
DictInsert(catA,"prayers","35");
DictInsert(catA,"mind","35");
DictInsert(catA,"koran","35");
DictInsert(catA,"monotheism","35");
DictInsert(catA,"healing","35");
DictInsert(catA,"confucianism","35");


/**************************************************************/
//doc37_sciencedd.txt
DictInsert(catA,"science","36");
DictInsert(catA,"color","36");
DictInsert(catA,"stars","36");
DictInsert(catA,"space","36");
DictInsert(catA,"materials","36");
DictInsert(catA,"gravity","36");
DictInsert(catA,"evolution","36");
DictInsert(catA,"schemes","36");
DictInsert(catA,"light","36");
DictInsert(catA,"physics","36");
DictInsert(catA,"eyes","36");
DictInsert(catA,"spectrum","36");
DictInsert(catA,"geology","36");
DictInsert(catA,"optics","36");
DictInsert(catA,"visible","36");
DictInsert(catA,"electromagnetic","36");
DictInsert(catA,"vision","36");
DictInsert(catA,"engineering","36");
DictInsert(catA,"colors","36");
DictInsert(catA,"biology","36");
DictInsert(catA,"planetary","36");
DictInsert(catA,"extraterrestrial","36");
DictInsert(catA,"deficiency","36");
DictInsert(catA,"exploration","36");
DictInsert(catA,"time","36");
DictInsert(catA,"astronomy","36");
DictInsert(catA,"thermodynamics","36");


/**************************************************************/
//doc38_sportsddd.txt
DictInsert(catA,"madrid","37");
DictInsert(catA,"yahoo","37");
DictInsert(catA,"manchester","37");
DictInsert(catA,"nba","37");
DictInsert(catA,"ham","37");
DictInsert(catA,"hockey","37");
DictInsert(catA,"psg","37");
DictInsert(catA,"paris","37");
DictInsert(catA,"fantasy","37");
DictInsert(catA,"formula","37");
DictInsert(catA,"serie","37");
DictInsert(catA,"united","37");
DictInsert(catA,"arsenal","37");
DictInsert(catA,"clips","37");
DictInsert(catA,"basketball","37");
DictInsert(catA,"tottenham","37");
DictInsert(catA,"dortmund","37");
DictInsert(catA,"sports","37");
DictInsert(catA,"laliga","37");
DictInsert(catA,"golf","37");
DictInsert(catA,"epl","37");
DictInsert(catA,"baseball","37");
DictInsert(catA,"liverpool","37");
DictInsert(catA,"borussia","37");
DictInsert(catA,"roma","37");
DictInsert(catA,"barcelona","37");
DictInsert(catA,"west","37");
DictInsert(catA,"boxing","37");
DictInsert(catA,"germany","37");
DictInsert(catA,"newcastle","37");
DictInsert(catA,"hibbett","37");
DictInsert(catA,"volleyball","37");
DictInsert(catA,"rugby","37");
DictInsert(catA,"ufc","37");
DictInsert(catA,"cricket","37");
DictInsert(catA,"goal","37");
DictInsert(catA,"juventus","37");
DictInsert(catA,"sport","37");
DictInsert(catA,"tennis","37");
DictInsert(catA,"hotspur","37");
DictInsert(catA,"saint","37");
DictInsert(catA,"everton","37");
DictInsert(catA,"bundesliga","37");
DictInsert(catA,"nfl","37");
DictInsert(catA,"munich","37");
DictInsert(catA,"chelsea","37");
DictInsert(catA,"academy","37");
DictInsert(catA,"ice","37");
DictInsert(catA,"table","37");
DictInsert(catA,"bayern","37");
DictInsert(catA,"athletico","37");
DictInsert(catA,"motogp","37");
DictInsert(catA,"soccer","37");
DictInsert(catA,"halftime","37");
DictInsert(catA,"athletics","37");
DictInsert(catA,"football","37");
DictInsert(catA,"milan","37");
DictInsert(catA,"real","37");
DictInsert(catA,"espn","37");


/**************************************************************/
//doc39_technolog.txt
DictInsert(catA,"science","38");
DictInsert(catA,"online","38");
DictInsert(catA,"information","38");
DictInsert(catA,"payment","38");
DictInsert(catA,"platform-as-a-service","38");
DictInsert(catA,"tools","38");
DictInsert(catA,"sheets","38");
DictInsert(catA,"design","38");
DictInsert(catA,"retrieval","38");
DictInsert(catA,"websites","38");
DictInsert(catA,"combinator","38");
DictInsert(catA,"development","38");
DictInsert(catA,"javascript","38");
DictInsert(catA,"cascading","38");
DictInsert(catA,"strategy","38");
DictInsert(catA,"phones","38");
DictInsert(catA,"mobile","38");
DictInsert(catA,"applications","38");
DictInsert(catA,"html","38");
DictInsert(catA,"valley","38");
DictInsert(catA,"technology","38");
DictInsert(catA,"computer","38");
DictInsert(catA,"experience","38");
DictInsert(catA,"internet","38");
DictInsert(catA,"wordpress","38");
DictInsert(catA,"digital","38");
DictInsert(catA,"payments","38");
DictInsert(catA,"style","38");
DictInsert(catA,"publishing","38");
DictInsert(catA,"computing","38");
DictInsert(catA,"programming","38");
DictInsert(catA,"paas","38");
DictInsert(catA,"shopping","38");
DictInsert(catA,"user","38");
DictInsert(catA,"services","38");
DictInsert(catA,"media","38");
DictInsert(catA,"engineering","38");
DictInsert(catA,"web","38");
DictInsert(catA,"collaboration","38");
DictInsert(catA,"cloud","38");
DictInsert(catA,"software","38");
DictInsert(catA,"silicon","38");
DictInsert(catA,"marketing","38");
DictInsert(catA,"interface","38");
DictInsert(catA,"saas","38");
DictInsert(catA,"usability","38");
DictInsert(catA,"trends","38");
DictInsert(catA,"scalability","38");


/**************************************************************/
//doc40_traveltou.txt
DictInsert(catA,"insurance","39");
DictInsert(catA,"agent","39");
DictInsert(catA,"tourism","39");
DictInsert(catA,"packages","39");
DictInsert(catA,"backpackers","39");
DictInsert(catA,"trip","39");
DictInsert(catA,"attraction","39");
DictInsert(catA,"agency","39");
DictInsert(catA,"road","39");
DictInsert(catA,"grand","39");
DictInsert(catA,"costco","39");
DictInsert(catA,"travel","39");
DictInsert(catA,"vacations","39");
DictInsert(catA,"planner","39");
DictInsert(catA,"kayak","39");
DictInsert(catA,"luggage","39");
DictInsert(catA,"ecotourism","39");
DictInsert(catA,"attractions","39");
DictInsert(catA,"tourist","39");
DictInsert(catA,"advisor","39");
DictInsert(catA,"tsa","39");
DictInsert(catA,"hospitality","39");
DictInsert(catA,"mta","39");
DictInsert(catA,"trailer","39");
DictInsert(catA,"visited","39");
DictInsert(catA,"suitcase","39");
DictInsert(catA,"pre-check","39");
DictInsert(catA,"flight","39");


/**************************************************************/
//doc41_videogame.txt
DictInsert(catA,"console","40");
DictInsert(catA,"nintendo","40");
DictInsert(catA,"nick","40");
DictInsert(catA,"video","40");
DictInsert(catA,"nba","40");
DictInsert(catA,"playstation","40");
DictInsert(catA,"call","40");
DictInsert(catA,"pacman","40");
DictInsert(catA,"xbox","40");
DictInsert(catA,"batman","40");
DictInsert(catA,"duty","40");
DictInsert(catA,"minecraft","40");
DictInsert(catA,"witcher","40");
DictInsert(catA,"arkham","40");
DictInsert(catA,"mario","40");
DictInsert(catA,"street","40");
DictInsert(catA,"switch","40");
DictInsert(catA,"nfl","40");
DictInsert(catA,"games","40");
DictInsert(catA,"skylanders","40");
DictInsert(catA,"madden","40");
DictInsert(catA,"retro","40");


return catA;

}


Dict getCatB(){

/*Categories ici*/
Dict catB;
catB=DictCreate();

/**************************************************************/
//doc01_artdesign.txt
DictInsert(catB,"икона","0");
DictInsert(catB,"инфографика","0");
DictInsert(catB,"воображение","0");
DictInsert(catB,"google","0");
DictInsert(catB,"логотип","0");
DictInsert(catB,"шрифт","0");
DictInsert(catB,"фото","0");
DictInsert(catB,"дизайн","0");
DictInsert(catB,"редактирование","0");
DictInsert(catB,"иконография","0");
DictInsert(catB,"шрифты","0");
DictInsert(catB,"компьютер","0");
DictInsert(catB,"обработка","0");
DictInsert(catB,"камера","0");
DictInsert(catB,"иконки","0");
DictInsert(catB,"искусство","0");
DictInsert(catB,"картина","0");
DictInsert(catB,"эскиз","0");
DictInsert(catB,"камеры","0");
DictInsert(catB,"изображений","0");
DictInsert(catB,"идентификация","0");
DictInsert(catB,"визуальный","0");
DictInsert(catB,"фотография","0");
DictInsert(catB,"вектор","0");
DictInsert(catB,"подход","0");
DictInsert(catB,"логотипы","0");
DictInsert(catB,"взаимодействие","0");
DictInsert(catB,"творческий","0");
DictInsert(catB,"художники","0");
DictInsert(catB,"рисование","0");
DictInsert(catB,"графика","0");
DictInsert(catB,"цифровой","0");
DictInsert(catB,"иллюстрация","0");
DictInsert(catB,"картины","0");
DictInsert(catB,"иллюстраторы","0");
DictInsert(catB,"дизайнеров","0");
DictInsert(catB,"графический","0");


/**************************************************************/
//doc02_betsgambl.txt
DictInsert(catB,"делать","1");
DictInsert(catB,"порядок","1");
DictInsert(catB,"онлайн","1");
DictInsert(catB,"продажа","1");
DictInsert(catB,"длинная","1");
DictInsert(catB,"покупка","1");
DictInsert(catB,"стена","1");
DictInsert(catB,"игроки","1");
DictInsert(catB,"опции","1");
DictInsert(catB,"миллион","1");
DictInsert(catB,"деньги","1");
DictInsert(catB,"сделка","1");
DictInsert(catB,"фонды","1");
DictInsert(catB,"живая","1");
DictInsert(catB,"азартная","1");
DictInsert(catB,"изгородь","1");
DictInsert(catB,"торговцы","1");
DictInsert(catB,"улица","1");
DictInsert(catB,"пари","1");
DictInsert(catB,"игра","1");
DictInsert(catB,"азартные","1");
DictInsert(catB,"рисковать","1");
DictInsert(catB,"цены","1");
DictInsert(catB,"ставку","1");
DictInsert(catB,"ставки","1");
DictInsert(catB,"казино","1");
DictInsert(catB,"продавать","1");
DictInsert(catB,"торговля","1");
DictInsert(catB,"интернет","1");
DictInsert(catB,"игры","1");
DictInsert(catB,"убытки","1");


/**************************************************************/
//doc03_booksdddd.txt
DictInsert(catB,"вымышленный","2");
DictInsert(catB,"рекомендации","2");
DictInsert(catB,"детский","2");
DictInsert(catB,"художественная","2");
DictInsert(catB,"публикация","2");
DictInsert(catB,"взрослый","2");
DictInsert(catB,"молодой","2");
DictInsert(catB,"книги","2");
DictInsert(catB,"издательский","2");
DictInsert(catB,"читатели","2");
DictInsert(catB,"литературный","2");
DictInsert(catB,"ibooks","2");
DictInsert(catB,"электронные","2");
DictInsert(catB,"получение","2");
DictInsert(catB,"самостоятельная","2");
DictInsert(catB,"авторы","2");
DictInsert(catB,"разжечь","2");
DictInsert(catB,"короткий","2");
DictInsert(catB,"поэзия","2");
DictInsert(catB,"рассказы","2");
DictInsert(catB,"нехудожественная","2");
DictInsert(catB,"символы","2");
DictInsert(catB,"американец","2");
DictInsert(catB,"книга","2");
DictInsert(catB,"литература","2");
DictInsert(catB,"фантазия","2");
DictInsert(catB,"электронная","2");
DictInsert(catB,"опубликовано","2");


/**************************************************************/
//doc04_businesse.txt
DictInsert(catB,"управление","3");
DictInsert(catB,"кирпич","3");
DictInsert(catB,"поведение","3");
DictInsert(catB,"местный","3");
DictInsert(catB,"владелец","3");
DictInsert(catB,"промышленное","3");
DictInsert(catB,"отношения","3");
DictInsert(catB,"импорт","3");
DictInsert(catB,"организационная","3");
DictInsert(catB,"организация","3");
DictInsert(catB,"социальное","3");
DictInsert(catB,"предприниматели","3");
DictInsert(catB,"планы","3");
DictInsert(catB,"дизайн","3");
DictInsert(catB,"для","3");
DictInsert(catB,"консультации","3");
DictInsert(catB,"маркетинг","3");
DictInsert(catB,"лидеры","3");
DictInsert(catB,"стратегия","3");
DictInsert(catB,"миномет","3");
DictInsert(catB,"предприятие","3");
DictInsert(catB,"культура","3");
DictInsert(catB,"мсп","3");
DictInsert(catB,"администрация","3");
DictInsert(catB,"бизнесы","3");
DictInsert(catB,"человек","3");
DictInsert(catB,"розничная","3");
DictInsert(catB,"модели","3");
DictInsert(catB,"экспорт","3");
DictInsert(catB,"проект","3");
DictInsert(catB,"маленький","3");
DictInsert(catB,"стратегический","3");
DictInsert(catB,"средняя","3");
DictInsert(catB,"компании","3");
DictInsert(catB,"лидерство","3");
DictInsert(catB,"бизнеса","3");
DictInsert(catB,"агентства","3");
DictInsert(catB,"совет","3");
DictInsert(catB,"сети","3");
DictInsert(catB,"торговля","3");
DictInsert(catB,"цифровой","3");
DictInsert(catB,"ресурсы","3");
DictInsert(catB,"предпринимательство","3");
DictInsert(catB,"электронная","3");
DictInsert(catB,"бизнес","3");


/**************************************************************/
//doc05_carsother.txt
DictInsert(catB,"центр","4");
DictInsert(catB,"передвижения","4");
DictInsert(catB,"грузовые","4");
DictInsert(catB,"продажа","4");
DictInsert(catB,"тесла","4");
DictInsert(catB,"toyota","4");
DictInsert(catB,"корвет","4");
DictInsert(catB,"модель","4");
DictInsert(catB,"герц","4");
DictInsert(catB,"продажи","4");
DictInsert(catB,"автомобиль","4");
DictInsert(catB,"honda","4");
DictInsert(catB,"форд","4");
DictInsert(catB,"crv","4");
DictInsert(catB,"автомобили","4");
DictInsert(catB,"грузовая","4");
DictInsert(catB,"дилерский","4");
DictInsert(catB,"мыть","4");
DictInsert(catB,"машина","4");
DictInsert(catB,"аренда","4");
DictInsert(catB,"дилер","4");
DictInsert(catB,"части","4");
DictInsert(catB,"средство","4");
DictInsert(catB,"авто","4");
DictInsert(catB,"легковые","4");
DictInsert(catB,"часть","4");
DictInsert(catB,"бмв","4");
DictInsert(catB,"используемый","4");


/**************************************************************/
//doc06_celebriti.txt
DictInsert(catB,"дженниффер","5");
DictInsert(catB,"жизнь","5");
DictInsert(catB,"исполнители","5");
DictInsert(catB,"крис","5");
DictInsert(catB,"сановники","5");
DictInsert(catB,"привычка","5");
DictInsert(catB,"слава","5");
DictInsert(catB,"знаменитости","5");
DictInsert(catB,"к","5");
DictInsert(catB,"брэд","5");
DictInsert(catB,"люди","5");
DictInsert(catB,"лопес","5");
DictInsert(catB,"стиль","5");
DictInsert(catB,"знатные","5");
DictInsert(catB,"знаменитость","5");
DictInsert(catB,"личности","5");
DictInsert(catB,"кардашьян","5");
DictInsert(catB,"цифры","5");
DictInsert(catB,"зендая","5");
DictInsert(catB,"кайли","5");
DictInsert(catB,"дженнер","5");
DictInsert(catB,"питт","5");
DictInsert(catB,"существованию","5");
DictInsert(catB,"избранные","5");
DictInsert(catB,"художники","5");
DictInsert(catB,"артисты","5");
DictInsert(catB,"средства","5");
DictInsert(catB,"эванс","5");
DictInsert(catB,"жизни","5");
DictInsert(catB,"ким","5");


/**************************************************************/
//doc07_cryptocur.txt
DictInsert(catB,"binance","6");
DictInsert(catB,"точка","6");
DictInsert(catB,"криптовалюта","6");
DictInsert(catB,"биткойн","6");
DictInsert(catB,"цепи","6");
DictInsert(catB,"кэш","6");
DictInsert(catB,"звено","6");
DictInsert(catB,"btc","6");
DictInsert(catB,"ltc","6");
DictInsert(catB,"в","6");
DictInsert(catB,"litecoin","6");
DictInsert(catB,"криптовалюты","6");
DictInsert(catB,"ethereum","6");
DictInsert(catB,"xmr","6");
DictInsert(catB,"ada","6");
DictInsert(catB,"bnb","6");
DictInsert(catB,"кардано","6");
DictInsert(catB,"привязь","6");
DictInsert(catB,"bch","6");
DictInsert(catB,"usdt","6");
DictInsert(catB,"крипто","6");
DictInsert(catB,"монета","6");
DictInsert(catB,"монеро","6");
DictInsert(catB,"xlm","6");
DictInsert(catB,"валюта","6");
DictInsert(catB,"горошек","6");
DictInsert(catB,"eth","6");
DictInsert(catB,"звездный","6");


/**************************************************************/
//doc08_cultureev.txt
DictInsert(catB,"события","7");
DictInsert(catB,"традиция","7");
DictInsert(catB,"этос","7");
DictInsert(catB,"межкультурный","7");
DictInsert(catB,"традиции","7");
DictInsert(catB,"образ","7");
DictInsert(catB,"мультикультурализм","7");
DictInsert(catB,"наследие","7");
DictInsert(catB,"мышления","7");
DictInsert(catB,"мероприятие","7");
DictInsert(catB,"культура","7");
DictInsert(catB,"отношение","7");
DictInsert(catB,"философия","7");
DictInsert(catB,"культурно","7");


/**************************************************************/
//doc09_curiousfa.txt
DictInsert(catB,"вопрос","8");
DictInsert(catB,"знания","8");
DictInsert(catB,"знать","8");
DictInsert(catB,"любопытство","8");
DictInsert(catB,"факты","8");
DictInsert(catB,"изысканный","8");
DictInsert(catB,"любопытный","8");


/**************************************************************/
//doc10_directori.txt
DictInsert(catB,"каталоги","9");
DictInsert(catB,"бот","9");
DictInsert(catB,"каналы","9");
DictInsert(catB,"боты","9");


/**************************************************************/
//doc11_economyfi.txt
DictInsert(catB,"финансы","10");
DictInsert(catB,"макрос","10");
DictInsert(catB,"финансирование","10");
DictInsert(catB,"частный","10");
DictInsert(catB,"повседневная","10");
DictInsert(catB,"жизнь","10");
DictInsert(catB,"капитализм","10");
DictInsert(catB,"математика","10");
DictInsert(catB,"деньги","10");
DictInsert(catB,"история","10");
DictInsert(catB,"валюты","10");
DictInsert(catB,"учет","10");
DictInsert(catB,"инвесторам","10");
DictInsert(catB,"экономия","10");
DictInsert(catB,"экономика","10");
DictInsert(catB,"сбор","10");
DictInsert(catB,"личное","10");
DictInsert(catB,"капитал","10");
DictInsert(catB,"рынок","10");
DictInsert(catB,"бухгалтерский","10");
DictInsert(catB,"инфляция","10");
DictInsert(catB,"микроэкономика","10");
DictInsert(catB,"экономическая","10");
DictInsert(catB,"инвестирование","10");
DictInsert(catB,"налоги","10");
DictInsert(catB,"средств","10");
DictInsert(catB,"акции","10");


/**************************************************************/
//doc12_education.txt
DictInsert(catB,"педагогика","11");
DictInsert(catB,"сельское","11");
DictInsert(catB,"в","11");
DictInsert(catB,"математика","11");
DictInsert(catB,"учебные","11");
DictInsert(catB,"понимаю","11");
DictInsert(catB,"инструкция","11");
DictInsert(catB,"планы","11");
DictInsert(catB,"учебная","11");
DictInsert(catB,"наука","11");
DictInsert(catB,"дело","11");
DictInsert(catB,"химия","11");
DictInsert(catB,"коммерция","11");
DictInsert(catB,"подготовка","11");
DictInsert(catB,"биология","11");
DictInsert(catB,"учителя","11");
DictInsert(catB,"урок","11");
DictInsert(catB,"домашнее","11");
DictInsert(catB,"статистика","11");
DictInsert(catB,"программа","11");
DictInsert(catB,"география","11");
DictInsert(catB,"школы","11");
DictInsert(catB,"учеба","11");
DictInsert(catB,"физика","11");
DictInsert(catB,"обучение","11");
DictInsert(catB,"школе","11");
DictInsert(catB,"хозяйство","11");
DictInsert(catB,"уроки","11");
DictInsert(catB,"образование","11");
DictInsert(catB,"учить","11");
DictInsert(catB,"школа","11");
DictInsert(catB,"инженерное","11");


/**************************************************************/
//doc13_eroticcon.txt
DictInsert(catB,"блядь","12");
DictInsert(catB,"секс","12");
DictInsert(catB,"белье","12");
DictInsert(catB,"дамское","12");
DictInsert(catB,"сексуальный","12");
DictInsert(catB,"любить","12");
DictInsert(catB,"гей","12");
DictInsert(catB,"кино","12");
DictInsert(catB,"порно","12");
DictInsert(catB,"содержание","12");
DictInsert(catB,"чувственный","12");
DictInsert(catB,"порнографический","12");
DictInsert(catB,"транссексуал","12");
DictInsert(catB,"влагалище","12");
DictInsert(catB,"дик","12");
DictInsert(catB,"подросток","12");
DictInsert(catB,"лесбиянка","12");
DictInsert(catB,"эротический","12");
DictInsert(catB,"вице","12");
DictInsert(catB,"обнаженные","12");
DictInsert(catB,"бля","12");
DictInsert(catB,"горячей","12");
DictInsert(catB,"киска","12");
DictInsert(catB,"нагота","12");
DictInsert(catB,"лизать","12");
DictInsert(catB,"мамаша","12");


/**************************************************************/
//doc14_fashionbe.txt
DictInsert(catB,"одежда","13");
DictInsert(catB,"платья","13");
DictInsert(catB,"мужской","13");
DictInsert(catB,"милый","13");
DictInsert(catB,"женский","13");
DictInsert(catB,"манера","13");
DictInsert(catB,"укладка","13");
DictInsert(catB,"женщины","13");
DictInsert(catB,"стиль","13");
DictInsert(catB,"красота","13");
DictInsert(catB,"мода","13");
DictInsert(catB,"снаряжение","13");
DictInsert(catB,"наряд","13");
DictInsert(catB,"ковать","13");
DictInsert(catB,"ткань","13");
DictInsert(catB,"фигура","13");
DictInsert(catB,"платье","13");


/**************************************************************/
//doc15_fitnessdd.txt
DictInsert(catB,"тренировка","14");
DictInsert(catB,"здоровье","14");
DictInsert(catB,"изгой","14");
DictInsert(catB,"телосложение","14");
DictInsert(catB,"физическая","14");
DictInsert(catB,"выносливость","14");
DictInsert(catB,"зал","14");
DictInsert(catB,"упражнения","14");
DictInsert(catB,"тренажерный","14");
DictInsert(catB,"фитнес-аэробика","14");
DictInsert(catB,"пресс","14");
DictInsert(catB,"фитнес","14");


/**************************************************************/
//doc16_foodcooki.txt
DictInsert(catB,"питательная","15");
DictInsert(catB,"смешанная","15");
DictInsert(catB,"рецепт","15");
DictInsert(catB,"кухня","15");
DictInsert(catB,"морепродукты","15");
DictInsert(catB,"плита","15");
DictInsert(catB,"ужина","15");
DictInsert(catB,"ктченс","15");
DictInsert(catB,"выпечка","15");
DictInsert(catB,"подождите","15");
DictInsert(catB,"пища","15");
DictInsert(catB,"десерт","15");
DictInsert(catB,"кулинария","15");
DictInsert(catB,"минут","15");
DictInsert(catB,"куриная","15");
DictInsert(catB,"еда","15");
DictInsert(catB,"поваренная","15");
DictInsert(catB,"есть","15");
DictInsert(catB,"печь","15");
DictInsert(catB,"книга","15");
DictInsert(catB,"жарка","15");
DictInsert(catB,"грудка","15");
DictInsert(catB,"изысканный","15");
DictInsert(catB,"рецепты","15");


/**************************************************************/
//doc17_foreignla.txt
DictInsert(catB,"изучение","16");
DictInsert(catB,"произносить","16");
DictInsert(catB,"языка","16");
DictInsert(catB,"произношение","16");
DictInsert(catB,"учиться","16");
DictInsert(catB,"говорить","16");
DictInsert(catB,"бегло","16");


/**************************************************************/
//doc18_healthmed.txt
DictInsert(catB,"здоровье","17");
DictInsert(catB,"больной","17");
DictInsert(catB,"лекарство","17");
DictInsert(catB,"кашля","17");
DictInsert(catB,"аллергия","17");
DictInsert(catB,"вес","17");
DictInsert(catB,"артериальное","17");
DictInsert(catB,"изжога","17");
DictInsert(catB,"депрессия","17");
DictInsert(catB,"антигистаминный","17");
DictInsert(catB,"уход","17");
DictInsert(catB,"травами","17");
DictInsert(catB,"от","17");
DictInsert(catB,"инфекции","17");
DictInsert(catB,"ангина","17");
DictInsert(catB,"эпидемиология","17");
DictInsert(catB,"болезнь","17");
DictInsert(catB,"лечение","17");
DictInsert(catB,"давление","17");
DictInsert(catB,"средство","17");
DictInsert(catB,"дрожжевые","17");
DictInsert(catB,"обезболивающее","17");
DictInsert(catB,"лекарства","17");


/**************************************************************/
//doc19_historydd.txt
DictInsert(catB,"мир","18");
DictInsert(catB,"войны","18");
DictInsert(catB,"тактика","18");
DictInsert(catB,"национальный","18");
DictInsert(catB,"черный","18");
DictInsert(catB,"музей","18");
DictInsert(catB,"хроника","18");
DictInsert(catB,"правительство","18");
DictInsert(catB,"история","18");
DictInsert(catB,"военные","18");
DictInsert(catB,"истории","18");
DictInsert(catB,"война","18");
DictInsert(catB,"время","18");
DictInsert(catB,"битва","18");
DictInsert(catB,"краткое","18");


/**************************************************************/
//doc20_hobbiesac.txt
DictInsert(catB,"интересы","19");
DictInsert(catB,"хобби","19");
DictInsert(catB,"деятельность","19");
DictInsert(catB,"общие","19");


/**************************************************************/
//doc21_homearchi.txt
DictInsert(catB,"архитектурный","20");
DictInsert(catB,"архитектор","20");
DictInsert(catB,"двор","20");
DictInsert(catB,"планы","20");
DictInsert(catB,"дизайн","20");
DictInsert(catB,"стиль","20");
DictInsert(catB,"ремесленный","20");
DictInsert(catB,"века","20");
DictInsert(catB,"середины","20");
DictInsert(catB,"жилые","20");
DictInsert(catB,"современный","20");
DictInsert(catB,"викторианские","20");
DictInsert(catB,"дома","20");
DictInsert(catB,"колониальные","20");
DictInsert(catB,"архитектура","20");
DictInsert(catB,"традиционные","20");
DictInsert(catB,"архитекторы","20");
DictInsert(catB,"тюдоровские","20");
DictInsert(catB,"современные","20");


/**************************************************************/
//doc22_humormeme.txt
DictInsert(catB,"мемы","21");
DictInsert(catB,"аниме","21");
DictInsert(catB,"приколы","21");
DictInsert(catB,"смешные","21");
DictInsert(catB,"юмор","21");
DictInsert(catB,"темные","21");


/**************************************************************/
//doc23_investmen.txt
DictInsert(catB,"авторском","22");
DictInsert(catB,"инвестировать","22");
DictInsert(catB,"слияния","22");
DictInsert(catB,"прав","22");
DictInsert(catB,"взлома","22");
DictInsert(catB,"рост","22");
DictInsert(catB,"купить","22");
DictInsert(catB,"нарушение","22");
DictInsert(catB,"собственность","22");
DictInsert(catB,"инновации","22");
DictInsert(catB,"найма","22");
DictInsert(catB,"финансирования","22");
DictInsert(catB,"компенсация","22");
DictInsert(catB,"молодых","22");
DictInsert(catB,"открытые","22");
DictInsert(catB,"интеллектуальная","22");
DictInsert(catB,"патенты","22");
DictInsert(catB,"об","22");
DictInsert(catB,"начального","22");
DictInsert(catB,"стартапы","22");
DictInsert(catB,"товарных","22");
DictInsert(catB,"оценка","22");
DictInsert(catB,"соучредители","22");
DictInsert(catB,"продать","22");
DictInsert(catB,"бизнес-идеи","22");
DictInsert(catB,"инвестиции","22");
DictInsert(catB,"предпусковые","22");
DictInsert(catB,"приобретений","22");
DictInsert(catB,"предпринимателей","22");
DictInsert(catB,"удержать","22");
DictInsert(catB,"капитала","22");
DictInsert(catB,"рынок","22");
DictInsert(catB,"цена","22");
DictInsert(catB,"идеи","22");
DictInsert(catB,"фирмы","22");
DictInsert(catB,"привлечение","22");
DictInsert(catB,"знаков","22");
DictInsert(catB,"венчурного","22");
DictInsert(catB,"инвестирование","22");
DictInsert(catB,"интернет","22");
DictInsert(catB,"за","22");
DictInsert(catB,"авторских","22");
DictInsert(catB,"инновационные","22");
DictInsert(catB,"праве","22");
DictInsert(catB,"закон","22");
DictInsert(catB,"фьючерс","22");
DictInsert(catB,"фондовый","22");
DictInsert(catB,"краудфандинг","22");


/**************************************************************/
//doc24_joblistin.txt
DictInsert(catB,"предоставлением","23");
DictInsert(catB,"ищу","23");
DictInsert(catB,"знаний","23");
DictInsert(catB,"связанные","23");
DictInsert(catB,"наилучший","23");
DictInsert(catB,"клиентская","23");
DictInsert(catB,"услуги,","23");
DictInsert(catB,"работы","23");
DictInsert(catB,"компьютер","23");
DictInsert(catB,"информация","23");
DictInsert(catB,"приложений","23");
DictInsert(catB,"опыт","23");
DictInsert(catB,"независимое","23");
DictInsert(catB,"возможность","23");
DictInsert(catB,"понимание","23");
DictInsert(catB,"степень","23");
DictInsert(catB,"обеспечения","23");
DictInsert(catB,"проекта","23");
DictInsert(catB,"умение","23");
DictInsert(catB,"обязанности","23");
DictInsert(catB,"по","23");
DictInsert(catB,"с","23");
DictInsert(catB,"требования","23");
DictInsert(catB,"школьные","23");
DictInsert(catB,"решения","23");
DictInsert(catB,"услуги","23");
DictInsert(catB,"разработки","23");
DictInsert(catB,"коммуникации","23");
DictInsert(catB,"клиенту","23");
DictInsert(catB,"продукт","23");
DictInsert(catB,"качество","23");
DictInsert(catB,"управление","23");
DictInsert(catB,"разработчиков","23");
DictInsert(catB,"кандидат","23");
DictInsert(catB,"позиции","23");
DictInsert(catB,"листинг","23");
DictInsert(catB,"дни","23");
DictInsert(catB,"для","23");
DictInsert(catB,"включая","23");
DictInsert(catB,"работа","23");
DictInsert(catB,"технического","23");
DictInsert(catB,"обеспечение","23");
DictInsert(catB,"компания","23");
DictInsert(catB,"технологии","23");
DictInsert(catB,"клиентам","23");
DictInsert(catB,"комплексный","23");
DictInsert(catB,"ответственного","23");
DictInsert(catB,"предприятием","23");
DictInsert(catB,"тренинги","23");
DictInsert(catB,"предоставление","23");
DictInsert(catB,"персонала","23");
DictInsert(catB,"программного","23");
DictInsert(catB,"групп","23");
DictInsert(catB,"пользователь","23");
DictInsert(catB,"к","23");
DictInsert(catB,"корпоративные","23");
DictInsert(catB,"среда","23");
DictInsert(catB,"проектов","23");
DictInsert(catB,"поездки","23");
DictInsert(catB,"на","23");
DictInsert(catB,"сервер","23");
DictInsert(catB,"|","23");
DictInsert(catB,"развития","23");
DictInsert(catB,"и","23");
DictInsert(catB,"процесса","23");
DictInsert(catB,"инжиниринг","23");
DictInsert(catB,"разработка","23");
DictInsert(catB,"команда","23");
DictInsert(catB,"требуемой","23");
DictInsert(catB,"контрактов","23");
DictInsert(catB,"или","23");
DictInsert(catB,"система","23");
DictInsert(catB,"назначены","23");
DictInsert(catB,"медицинские","23");
DictInsert(catB,"несколько","23");
DictInsert(catB,"инструменты","23");
DictInsert(catB,"работа,","23");
DictInsert(catB,"способного","23");
DictInsert(catB,"системы","23");
DictInsert(catB,"обслуживания","23");
DictInsert(catB,"уровень","23");
DictInsert(catB,"/","23");
DictInsert(catB,"руководство","23");
DictInsert(catB,"лет","23");
DictInsert(catB,"продажам","23");
DictInsert(catB,"производственная","23");
DictInsert(catB,"тестирование","23");
DictInsert(catB,"бизнес-данных","23");
DictInsert(catB,"сильная","23");
DictInsert(catB,"поддержка","23");
DictInsert(catB,"безопасности","23");
DictInsert(catB,"высокопоставленные","23");


/**************************************************************/
//doc25_kidsparen.txt
DictInsert(catB,"раскраски","24");
DictInsert(catB,"сарай,","24");
DictInsert(catB,"с","24");
DictInsert(catB,"воспитание","24");
DictInsert(catB,"для","24");
DictInsert(catB,"ног,","24");
DictInsert(catB,"шкафчик","24");
DictInsert(catB,"разговор","24");
DictInsert(catB,"родителями","24");
DictInsert(catB,"детей,","24");
DictInsert(catB,"гончарный","24");


/**************************************************************/
//doc26_marketing.txt
DictInsert(catB,"именование","25");
DictInsert(catB,"аффилированный","25");
DictInsert(catB,"названия","25");
DictInsert(catB,"спам","25");
DictInsert(catB,"продукта","25");
DictInsert(catB,"производство","25");
DictInsert(catB,"брендинга","25");
DictInsert(catB,"брендинг","25");
DictInsert(catB,"планирование","25");
DictInsert(catB,"новых","25");
DictInsert(catB,"гостевой","25");
DictInsert(catB,"выступления","25");
DictInsert(catB,"общественностью","25");
DictInsert(catB,"маркетинговая","25");
DictInsert(catB,"интернет-реклама","25");
DictInsert(catB,"бюллетени","25");
DictInsert(catB,"с","25");
DictInsert(catB,"агентства","25");
DictInsert(catB,"почта","25");
DictInsert(catB,"печатных","25");
DictInsert(catB,"электронная","25");
DictInsert(catB,"электронной","25");
DictInsert(catB,"девизы","25");
DictInsert(catB,"рекламные","25");
DictInsert(catB,"мобильные","25");
DictInsert(catB,"бюллетень","25");
DictInsert(catB,"информационные","25");
DictInsert(catB,"знакомство","25");
DictInsert(catB,"печать","25");
DictInsert(catB,"письма","25");
DictInsert(catB,"сми","25");
DictInsert(catB,"редактирование","25");
DictInsert(catB,"стратегия","25");
DictInsert(catB,"информационный","25");
DictInsert(catB,"узнаваемость","25");
DictInsert(catB,"график","25");
DictInsert(catB,"новыми","25");
DictInsert(catB,"совет","25");
DictInsert(catB,"блоги","25");
DictInsert(catB,"клиентов","25");
DictInsert(catB,"видео","25");
DictInsert(catB,"мероприятий","25");
DictInsert(catB,"коммерческие","25");
DictInsert(catB,"вещание","25");
DictInsert(catB,"клиенты","25");
DictInsert(catB,"в","25");
DictInsert(catB,"социальных","25");
DictInsert(catB,"доставка","25");
DictInsert(catB,"людьми","25");
DictInsert(catB,"лозунги","25");
DictInsert(catB,"связи","25");
DictInsert(catB,"онлайн-видео","25");
DictInsert(catB,"создание","25");
DictInsert(catB,"съезды","25");
DictInsert(catB,"друзей","25");
DictInsert(catB,"публичные","25");
DictInsert(catB,"медиа","25");
DictInsert(catB,"конференции","25");
DictInsert(catB,"хэштеги","25");
DictInsert(catB,"кинематография","25");
DictInsert(catB,"блог","25");
DictInsert(catB,"почты","25");
DictInsert(catB,"b2b","25");
DictInsert(catB,"персональный","25");
DictInsert(catB,"маркетинг","25");
DictInsert(catB,"бренды","25");
DictInsert(catB,"бренда","25");
DictInsert(catB,"контент-маркетинг","25");
DictInsert(catB,"теги","25");
DictInsert(catB,"профессиональные","25");
DictInsert(catB,"управления","25");
DictInsert(catB,"кинопроизводства","25");
DictInsert(catB,"пресс-релизы","25");
DictInsert(catB,"веб","25");
DictInsert(catB,"сети","25");
DictInsert(catB,"сетях","25");
DictInsert(catB,"репутацией","25");


/**************************************************************/
//doc27_motivatio.txt
DictInsert(catB,"разговоры","26");
DictInsert(catB,"цель","26");
DictInsert(catB,"вредные","26");
DictInsert(catB,"факторы","26");
DictInsert(catB,"управление","26");
DictInsert(catB,"навыки","26");
DictInsert(catB,"отвлечение","26");
DictInsert(catB,"привычки","26");
DictInsert(catB,"улучшение","26");
DictInsert(catB,"советы","26");
DictInsert(catB,"организация","26");
DictInsert(catB,"отвлекающие","26");
DictInsert(catB,"амбиции","26");
DictInsert(catB,"рутинные","26");
DictInsert(catB,"привычка","26");
DictInsert(catB,"личных","26");
DictInsert(catB,"баланс","26");
DictInsert(catB,"работы","26");
DictInsert(catB,"определение","26");
DictInsert(catB,"задачи","26");
DictInsert(catB,"постановка","26");
DictInsert(catB,"личная","26");
DictInsert(catB,"прокрастинация","26");
DictInsert(catB,"цели","26");
DictInsert(catB,"системы","26");
DictInsert(catB,"планирование","26");
DictInsert(catB,"мотивация","26");
DictInsert(catB,"хаки","26");
DictInsert(catB,"вдохновители","26");
DictInsert(catB,"вдохновение","26");
DictInsert(catB,"личной","26");
DictInsert(catB,"самосовершенствование","26");
DictInsert(catB,"и","26");
DictInsert(catB,"целей","26");
DictInsert(catB,"внимание","26");
DictInsert(catB,"обучение","26");
DictInsert(catB,"саморазвитие","26");
DictInsert(catB,"жизни","26");
DictInsert(catB,"умение","26");
DictInsert(catB,"концентрации","26");
DictInsert(catB,"рутинное","26");
DictInsert(catB,"задача","26");
DictInsert(catB,"продуктивность","26");
DictInsert(catB,"достижение","26");
DictInsert(catB,"мышление","26");
DictInsert(catB,"вдохновитель","26");
DictInsert(catB,"система","26");
DictInsert(catB,"успех","26");
DictInsert(catB,"действия","26");


/**************************************************************/
//doc28_moviesddd.txt
DictInsert(catB,"видео","27");
DictInsert(catB,"поттер","27");
DictInsert(catB,"бесплатно","27");
DictInsert(catB,"фильмы","27");
DictInsert(catB,"hbo","27");
DictInsert(catB,"гарри","27");
DictInsert(catB,"soap2day","27");
DictInsert(catB,"сезон","27");
DictInsert(catB,"hedgehog","27");
DictInsert(catB,"эпизод","27");
DictInsert(catB,"sonic","27");
DictInsert(catB,"netflix","27");
DictInsert(catB,"шоу","27");
DictInsert(catB,"замороженный","27");
DictInsert(catB,"фильма","27");
DictInsert(catB,"джентлен","27");
DictInsert(catB,"страшное","27");
DictInsert(catB,"лучшее","27");


/**************************************************************/
//doc29_musicdddd.txt
DictInsert(catB,"eminem","28");
DictInsert(catB,"мелодии","28");
DictInsert(catB,"играть","28");
DictInsert(catB,"яблоко","28");
DictInsert(catB,"загрузчик","28");
DictInsert(catB,"марс","28");
DictInsert(catB,"джаз","28");
DictInsert(catB,"spotify","28");
DictInsert(catB,"песня","28");
DictInsert(catB,"росс","28");
DictInsert(catB,"скачать","28");
DictInsert(catB,"mp3","28");
DictInsert(catB,"бруно","28");
DictInsert(catB,"звук","28");
DictInsert(catB,"youtube","28");
DictInsert(catB,"гитара","28");
DictInsert(catB,"андреа","28");
DictInsert(catB,"музыка","28");
DictInsert(catB,"бочелли","28");
DictInsert(catB,"рик","28");
DictInsert(catB,"ноты","28");


/**************************************************************/
//doc30_offerspro.txt
DictInsert(catB,"купон","29");
DictInsert(catB,"предложение","29");
DictInsert(catB,"промокод","29");
DictInsert(catB,"пятница","29");
DictInsert(catB,"распродажа","29");
DictInsert(catB,"черная","29");
DictInsert(catB,"скобы","29");
DictInsert(catB,"предлагает","29");
DictInsert(catB,"расширенная","29");
DictInsert(catB,"акции","29");
DictInsert(catB,"расширяется","29");
DictInsert(catB,"продвижение","29");
DictInsert(catB,"купоны","29");


/**************************************************************/
//doc31_petsddddd.txt
DictInsert(catB,"аквариумов","30");
DictInsert(catB,"насосы","30");
DictInsert(catB,"grooming","30");
DictInsert(catB,"бернские","30");
DictInsert(catB,"обрабатывают","30");
DictInsert(catB,"акита","30");
DictInsert(catB,"ньюфаундленд","30");
DictInsert(catB,"веществ","30");
DictInsert(catB,"papillon","30");
DictInsert(catB,"кошачьи","30");
DictInsert(catB,"освещение","30");
DictInsert(catB,"сырой","30");
DictInsert(catB,"поставщики","30");
DictInsert(catB,"мопс","30");
DictInsert(catB,"для","30");
DictInsert(catB,"обогреватели","30");
DictInsert(catB,"животные","30");
DictInsert(catB,"распродажа","30");
DictInsert(catB,"сырых","30");
DictInsert(catB,"фильтры","30");
DictInsert(catB,"органических","30");
DictInsert(catB,"щенки","30");
DictInsert(catB,"боксер","30");
DictInsert(catB,"полных","30");
DictInsert(catB,"собак","30");
DictInsert(catB,"домашние","30");
DictInsert(catB,"корм","30");
DictInsert(catB,"производители","30");
DictInsert(catB,"горы","30");
DictInsert(catB,"мальтийская","30");
DictInsert(catB,"аквариумы","30");


/**************************************************************/
//doc32_politicsi.txt
DictInsert(catB,"дорожная","31");
DictInsert(catB,"президент","31");
DictInsert(catB,"президентские","31");
DictInsert(catB,"независимый","31");
DictInsert(catB,"диктатор","31");
DictInsert(catB,"демократический","31");
DictInsert(catB,"обороны","31");
DictInsert(catB,"в","31");
DictInsert(catB,"стране","31");
DictInsert(catB,"демократ","31");
DictInsert(catB,"лиассон","31");
DictInsert(catB,"министра","31");
DictInsert(catB,"армия","31");
DictInsert(catB,"партии","31");
DictInsert(catB,"общее","31");
DictInsert(catB,"политика","31");
DictInsert(catB,"заместитель","31");
DictInsert(catB,"диктатура","31");
DictInsert(catB,"пожар","31");
DictInsert(catB,"выборы","31");
DictInsert(catB,"правительство","31");
DictInsert(catB,"инциденты","31");
DictInsert(catB,"полиция","31");
DictInsert(catB,"авария","31");
DictInsert(catB,"авиация","31");


/**************************************************************/
//doc33_psycholog.txt
DictInsert(catB,"нормы","32");
DictInsert(catB,"здоровье","32");
DictInsert(catB,"поведение","32");
DictInsert(catB,"повседневная","32");
DictInsert(catB,"отношения","32");
DictInsert(catB,"человеческое","32");
DictInsert(catB,"жизнь","32");
DictInsert(catB,"психиатрия","32");
DictInsert(catB,"поведенческие","32");
DictInsert(catB,"мораль","32");
DictInsert(catB,"myers","32");
DictInsert(catB,"типа","32");
DictInsert(catB,"диск","32");
DictInsert(catB,"эмоции","32");
DictInsert(catB,"личности","32");
DictInsert(catB,"психология","32");
DictInsert(catB,"невербальное","32");
DictInsert(catB,"тревожность","32");
DictInsert(catB,"общение","32");
DictInsert(catB,"entp","32");
DictInsert(catB,"черты","32");
DictInsert(catB,"психическое","32");
DictInsert(catB,"индикатор","32");
DictInsert(catB,"интроверты","32");
DictInsert(catB,"общество","32");
DictInsert(catB,"нейробиология","32");
DictInsert(catB,"философия","32");
DictInsert(catB,"briggs","32");
DictInsert(catB,"интроверсия","32");
DictInsert(catB,"тревога","32");
DictInsert(catB,"экстраверсия","32");
DictInsert(catB,"экстраверты","32");
DictInsert(catB,"совет","32");
DictInsert(catB,"intj","32");
DictInsert(catB,"infj","32");
DictInsert(catB,"ненормальная","32");
DictInsert(catB,"интроверт","32");
DictInsert(catB,"эмоция","32");
DictInsert(catB,"intp","32");
DictInsert(catB,"enfp","32");
DictInsert(catB,"майерс-бриггса","32");


/**************************************************************/
//doc34_realestat.txt
DictInsert(catB,"дом","33");
DictInsert(catB,"недвижимость","33");
DictInsert(catB,"адвокат","33");
DictInsert(catB,"коммерческий","33");
DictInsert(catB,"домов","33");
DictInsert(catB,"риэлтор","33");
DictInsert(catB,"продажа","33");
DictInsert(catB,"дома","33");
DictInsert(catB,"земельный","33");
DictInsert(catB,"покупка","33");
DictInsert(catB,"агент","33");
DictInsert(catB,"список","33");
DictInsert(catB,"масион","33");


/**************************************************************/
//doc35_recreatio.txt
DictInsert(catB,"центр","34");
DictInsert(catB,"креативная","34");
DictInsert(catB,"парки","34");
DictInsert(catB,"общественный","34");
DictInsert(catB,"открытом","34");
DictInsert(catB,"воздухе","34");
DictInsert(catB,"пламенеющее","34");
DictInsert(catB,"для","34");
DictInsert(catB,"терапевтический","34");
DictInsert(catB,"на","34");
DictInsert(catB,"город","34");
DictInsert(catB,"долина","34");
DictInsert(catB,"рек","34");
DictInsert(catB,"региональный","34");
DictInsert(catB,"скоттс","34");
DictInsert(catB,"отдых","34");
DictInsert(catB,"парк","34");
DictInsert(catB,"ущелье","34");
DictInsert(catB,"взрослых","34");
DictInsert(catB,"развлечений","34");
DictInsert(catB,"каньон","34");
DictInsert(catB,"мечты","34");
DictInsert(catB,"озеро","34");


/**************************************************************/
//doc36_religions.txt
DictInsert(catB,"атеист","35");
DictInsert(catB,"тора","35");
DictInsert(catB,"зороастризм","35");
DictInsert(catB,"просветление","35");
DictInsert(catB,"бог","35");
DictInsert(catB,"иегова","35");
DictInsert(catB,"духа","35");
DictInsert(catB,"христианство","35");
DictInsert(catB,"политеизм","35");
DictInsert(catB,"язычество","35");
DictInsert(catB,"мормон","35");
DictInsert(catB,"гностицизм","35");
DictInsert(catB,"духовное","35");
DictInsert(catB,"дух","35");
DictInsert(catB,"растафари","35");
DictInsert(catB,"бхудизм","35");
DictInsert(catB,"вера","35");
DictInsert(catB,"индуистский","35");
DictInsert(catB,"коран","35");
DictInsert(catB,"добрый","35");
DictInsert(catB,"плохой","35");
DictInsert(catB,"руководство","35");
DictInsert(catB,"монотеизм","35");
DictInsert(catB,"библия","35");
DictInsert(catB,"стихи","35");
DictInsert(catB,"истинное","35");
DictInsert(catB,"сантерия","35");
DictInsert(catB,"свидетель","35");
DictInsert(catB,"здравие","35");
DictInsert(catB,"агнотизм","35");
DictInsert(catB,"исцеление","35");
DictInsert(catB,"молитва","35");
DictInsert(catB,"религия","35");
DictInsert(catB,"языческий","35");
DictInsert(catB,"конфуцианство","35");
DictInsert(catB,"бхудха","35");
DictInsert(catB,"духовность","35");


/**************************************************************/
//doc37_sciencedd.txt
DictInsert(catB,"инженерия","36");
DictInsert(catB,"глаза","36");
DictInsert(catB,"время","36");
DictInsert(catB,"схемы","36");
DictInsert(catB,"геология","36");
DictInsert(catB,"наука","36");
DictInsert(catB,"цветового","36");
DictInsert(catB,"дефицит","36");
DictInsert(catB,"биология","36");
DictInsert(catB,"цвета","36");
DictInsert(catB,"космоса","36");
DictInsert(catB,"спектр","36");
DictInsert(catB,"внеземная","36");
DictInsert(catB,"эволюция","36");
DictInsert(catB,"астрономия","36");
DictInsert(catB,"космические","36");
DictInsert(catB,"физика","36");
DictInsert(catB,"оптика","36");
DictInsert(catB,"гравитация","36");
DictInsert(catB,"исследование","36");
DictInsert(catB,"звезды","36");
DictInsert(catB,"материалы","36");
DictInsert(catB,"видимый","36");
DictInsert(catB,"термодинамика","36");
DictInsert(catB,"зрения","36");
DictInsert(catB,"свет","36");
DictInsert(catB,"цветовые","36");
DictInsert(catB,"электромагнитный","36");
DictInsert(catB,"планетология","36");


/**************************************************************/
//doc38_sportsddd.txt
DictInsert(catB,"мадрид","37");
DictInsert(catB,"эпл","37");
DictInsert(catB,"бейсбол","37");
DictInsert(catB,"академия","37");
DictInsert(catB,"германия","37");
DictInsert(catB,"yahoo","37");
DictInsert(catB,"тоттенхэм","37");
DictInsert(catB,"лалига","37");
DictInsert(catB,"ньюкасл","37");
DictInsert(catB,"стол","37");
DictInsert(catB,"псж","37");
DictInsert(catB,"фентези","37");
DictInsert(catB,"хиббетт","37");
DictInsert(catB,"баскетбол","37");
DictInsert(catB,"боруссия","37");
DictInsert(catB,"вест","37");
DictInsert(catB,"крик","37");
DictInsert(catB,"клипы","37");
DictInsert(catB,"бавария","37");
DictInsert(catB,"эвертон","37");
DictInsert(catB,"ювентус","37");
DictInsert(catB,"челси","37");
DictInsert(catB,"футбол","37");
DictInsert(catB,"хэм","37");
DictInsert(catB,"спорт","37");
DictInsert(catB,"реал","37");
DictInsert(catB,"мюнхен","37");
DictInsert(catB,"нфл","37");
DictInsert(catB,"гол","37");
DictInsert(catB,"хоккей","37");
DictInsert(catB,"юнайтед","37");
DictInsert(catB,"рома","37");
DictInsert(catB,"сен","37");
DictInsert(catB,"бундеслига","37");
DictInsert(catB,"барселона","37");
DictInsert(catB,"ufc","37");
DictInsert(catB,"ливерпуль","37");
DictInsert(catB,"серия","37");
DictInsert(catB,"хотспур","37");
DictInsert(catB,"арсенал","37");
DictInsert(catB,"бокс","37");
DictInsert(catB,"атлетико","37");
DictInsert(catB,"манчестер","37");
DictInsert(catB,"гольф","37");
DictInsert(catB,"перерыв","37");
DictInsert(catB,"дортмунд","37");
DictInsert(catB,"спортивная","37");
DictInsert(catB,"нба","37");
DictInsert(catB,"motogp","37");
DictInsert(catB,"волейбол","37");
DictInsert(catB,"espn","37");
DictInsert(catB,"париж","37");


/**************************************************************/
//doc39_technolog.txt
DictInsert(catB,"использования","38");
DictInsert(catB,"компьютерные","38");
DictInsert(catB,"удобство","38");
DictInsert(catB,"мобильные","38");
DictInsert(catB,"инструменты","38");
DictInsert(catB,"тенденции","38");
DictInsert(catB,"пользователя","38");
DictInsert(catB,"платформа","38");
DictInsert(catB,"облачных","38");
DictInsert(catB,"кремниевой","38");
DictInsert(catB,"javascript","38");
DictInsert(catB,"программное","38");
DictInsert(catB,"услуга","38");
DictInsert(catB,"интерфейс","38");
DictInsert(catB,"программирование","38");
DictInsert(catB,"дизайн","38");
DictInsert(catB,"каскадные","38");
DictInsert(catB,"работы","38");
DictInsert(catB,"для","38");
DictInsert(catB,"маркетинг","38");
DictInsert(catB,"html","38");
DictInsert(catB,"науки","38");
DictInsert(catB,"обеспечение","38");
DictInsert(catB,"стратегии","38");
DictInsert(catB,"wordpress","38");
DictInsert(catB,"технологии","38");
DictInsert(catB,"масштабируемость","38");
DictInsert(catB,"комбинатор","38");
DictInsert(catB,"paas","38");
DictInsert(catB,"платежи","38");
DictInsert(catB,"телефоны","38");
DictInsert(catB,"публикации","38");
DictInsert(catB,"обеспечения","38");
DictInsert(catB,"долины","38");
DictInsert(catB,"как","38");
DictInsert(catB,"совместной","38");
DictInsert(catB,"разработка","38");
DictInsert(catB,"стилей","38");
DictInsert(catB,"поиск","38");
DictInsert(catB,"информации","38");
DictInsert(catB,"онлайн-магазины","38");
DictInsert(catB,"приложения","38");
DictInsert(catB,"веб-сайтов","38");
DictInsert(catB,"таблицы","38");
DictInsert(catB,"интернет","38");
DictInsert(catB,"цифровой","38");
DictInsert(catB,"saas","38");
DictInsert(catB,"веб-приложений","38");
DictInsert(catB,"услуги","38");
DictInsert(catB,"вычислений","38");
DictInsert(catB,"программного","38");
DictInsert(catB,"медиа","38");


/**************************************************************/
//doc40_traveltou.txt
DictInsert(catB,"грандиозный","39");
DictInsert(catB,"путешествия","39");
DictInsert(catB,"туризм","39");
DictInsert(catB,"отпуск","39");
DictInsert(catB,"туристов","39");
DictInsert(catB,"байдарках","39");
DictInsert(catB,"поездке","39");
DictInsert(catB,"багаж","39");
DictInsert(catB,"планированию","39");
DictInsert(catB,"стоимость","39");
DictInsert(catB,"советник","39");
DictInsert(catB,"посетили","39");
DictInsert(catB,"агентство","39");
DictInsert(catB,"рейс","39");
DictInsert(catB,"туристические","39");
DictInsert(catB,"страхование","39");
DictInsert(catB,"агент","39");
DictInsert(catB,"достопримечательности","39");
DictInsert(catB,"на","39");
DictInsert(catB,"гостеприимство","39");
DictInsert(catB,"чемодан","39");
DictInsert(catB,"tsa","39");
DictInsert(catB,"экотуризм","39");
DictInsert(catB,"по","39");
DictInsert(catB,"прицеп","39");
DictInsert(catB,"проверка","39");
DictInsert(catB,"mta","39");
DictInsert(catB,"предварительная","39");


/**************************************************************/
//doc41_videogame.txt
DictInsert(catB,"console","40");
DictInsert(catB,"ретро","40");
DictInsert(catB,"nintendo","40");
DictInsert(catB,"nick","40");
DictInsert(catB,"nba","40");
DictInsert(catB,"playstation","40");
DictInsert(catB,"call","40");
DictInsert(catB,"pacman","40");
DictInsert(catB,"xbox","40");
DictInsert(catB,"duty","40");
DictInsert(catB,"видеоигры","40");
DictInsert(catB,"ведьмак","40");
DictInsert(catB,"minecraft","40");
DictInsert(catB,"аркхем","40");
DictInsert(catB,"street","40");
DictInsert(catB,"бэтмен","40");
DictInsert(catB,"марио","40");
DictInsert(catB,"switch","40");
DictInsert(catB,"nfl","40");
DictInsert(catB,"skylanders","40");
DictInsert(catB,"madden","40");

return catB;

}



